### ISSUE TITLE
Foldable (HashMap k) is slower than it could be

### ISSUE THREAD

**Issue by Fuuzetsu** [haskell-unordered-containers/unordered-containers#222]
Currently the Foldable instance for HashMap only specifies `foldr`. While that's technically enough, it gives poor Core when we use something like `Foldable.foldl'` as it gets translated into a `foldr`, `id` gets passed a few layers down &c.

We could trivially define `Foldable.foldl' = HashMap.foldl'` which is already written, available and generates much better Core. Maybe some other methods should get the same treatment.

**Comment by Fuuzetsu** [comment]
Fixed by #223

**Comment by treeowl** [comment]
We still have some more methods to deal with. I'm working on them.

**Comment by googleson78** [comment]
Is this still active?

I think it would be best to define all the methods (`elem`/`null` are "dangerous" in this aspect, you wouldn't expect them to traverse the structure)

Same thing for `HashSet`

(This would also be nicely consistent with how `containers` defines all the methods)
